import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import {
  Copy, Check, Flame, FileText, Hash, Eye,
  Lightbulb, Sparkles, RotateCw, Share2,
  Twitter, Instagram, ThumbsUp, ThumbsDown,
  Table2, Download,
} from 'lucide-react';
import { ContentReviewPanel } from '@/components/features/ContentReviewPanel';

interface AIMessageProps {
  content: any;
  onRemix?: (iteration: number) => void;
  remixIteration?: number;
  messageId?: string;
}

// ── Storyboard detection ──────────────────────────────────────────────────────
function detectStoryboard(text: string): boolean {
  // A storyboard table has | Scene | header row
  return /\|\s*scene\s*\|/i.test(text) || /\|\s*---\s*\|/.test(text);
}

// ── Parse markdown table rows ─────────────────────────────────────────────────
function parseMarkdownTable(text: string): { headers: string[]; rows: string[][] } {
  const lines = text.split('\n').filter(l => l.trim().startsWith('|'));
  if (lines.length < 2) return { headers: [], rows: [] };
  const headers = lines[0].split('|').map(h => h.trim()).filter(Boolean);
  const rows: string[][] = [];
  for (let i = 2; i < lines.length; i++) {
    const cells = lines[i].split('|').map(c => c.trim()).filter(Boolean);
    if (cells.length > 0) rows.push(cells);
  }
  return { headers, rows };
}

// ── jsPDF storyboard export ───────────────────────────────────────────────────
async function exportStoryboardPDF(text: string, username: string) {
  const { jsPDF } = await import('jspdf');
  const { headers, rows } = parseMarkdownTable(text);
  if (!headers.length) return false;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();

  // ── Header bar ──
  doc.setFillColor(255, 229, 0); // electric yellow
  doc.rect(0, 0, pw, 18, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(28, 28, 30);
  doc.text('ViralForge AI — Content Storyboard', 14, 11.5);

  // ── Date + username watermark ──
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  doc.text(`@${username}  ·  ${now}`, pw - 14, 11.5, { align: 'right' });

  // ── Table ──
  const colW = (pw - 28) / headers.length;
  let y = 26;

  // Header row
  doc.setFillColor(42, 42, 42);
  doc.rect(14, y - 6, pw - 28, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 229, 0);
  headers.forEach((h, i) => {
    doc.text(h.toUpperCase(), 14 + colW * i + 2, y);
  });
  y += 8;

  // Data rows
  const LINE_H = 8;
  rows.forEach((row, ri) => {
    const isEven = ri % 2 === 0;
    doc.setFillColor(isEven ? 30 : 38, isEven ? 30 : 38, isEven ? 32 : 40);
    doc.rect(14, y - 5, pw - 28, LINE_H, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(220, 220, 220);
    row.forEach((cell, ci) => {
      const truncated = cell.length > 60 ? cell.substring(0, 57) + '...' : cell;
      doc.text(truncated, 14 + colW * ci + 2, y + 1);
    });
    y += LINE_H;
    if (y > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  });

  // ── Footer ──
  const ph = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by ViralForge AI — viralforge.ai', 14, ph - 6);

  doc.save(`viralforge-storyboard-${Date.now()}.pdf`);
  return true;
}

// ── Platform-specific copy formatters ────────────────────────────────────────
function formatForPlatform(content: any, platform: 'tiktok' | 'reels' | 'shorts'): string {
  const hook = content.hook || '';
  const script = content.script || '';
  const caption = content.caption || '';
  const hashtags = (content.hashtags || []).map((t: string) => `#${t}`).join(' ');

  switch (platform) {
    case 'tiktok': {
      // TikTok: hook + short caption (max ~150 chars) + top hashtags
      const shortCaption = caption.length > 150 ? caption.substring(0, 147) + '...' : caption;
      const topTags = (content.hashtags || []).slice(0, 8).map((t: string) => `#${t}`).join(' ');
      return `${hook}\n\n${shortCaption}\n\n${topTags}`;
    }
    case 'reels': {
      // Reels: emoji-heavy, full caption
      const emojiCaption = caption.replace(/\. /g, ' ✨ ').replace(/! /g, '! 🔥 ');
      return `${hook} 🎯\n\n${emojiCaption} 💯\n\n${hashtags}`;
    }
    case 'shorts': {
      // Shorts: no hashtags, just hook + script snippet
      const scriptSnip = script.length > 200 ? script.substring(0, 197) + '...' : script;
      return `${hook}\n\n${scriptSnip}`;
    }
  }
}

// ── Main component ────────────────────────────────────────────────────────────

export function AIMessage({ content, onRemix, remixIteration = 0, messageId }: AIMessageProps) {
  const { toast } = useToast();
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [shareOpen, setShareOpen] = useState(false);
  const [platformCopyOpen, setPlatformCopyOpen] = useState(false);
  const [exportingPDF, setExportingPDF] = useState(false);

  // Reaction state — persisted per message in localStorage
  const reactionKey = messageId ? `vf_reaction_${messageId}` : null;
  const [reaction, setReaction] = useState<'up' | 'down' | null>(() => {
    if (!reactionKey) return null;
    return (localStorage.getItem(reactionKey) as 'up' | 'down' | null);
  });

  const isStructuredContent =
    typeof content === 'object' && content !== null && 'hook' in content && 'script' in content;

  // Full text for chat messages
  const textContent = typeof content === 'string' ? content : JSON.stringify(content, null, 2);

  // Detect storyboard in any message
  const hasStoryboard = isStructuredContent
    ? detectStoryboard((content.script || '') + (content.postingTip || ''))
    : detectStoryboard(textContent);

  const storyboardText = isStructuredContent
    ? textContent + '\n' + (content.script || '')
    : textContent;

  const copyToClipboard = async (text: string, section: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedSection(section);
    toast({ title: 'Copied!', description: `${section} copied to clipboard` });
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const copyAll = async () => {
    let allText = '';
    if (isStructuredContent) {
      allText = `HOOK:\n${content.hook}\n\nSCRIPT:\n${content.script}\n\nCAPTION:\n${content.caption}\n\nHASHTAGS:\n${
        content.hashtags?.map((tag: string) => `#${tag}`).join(' ') || ''
      }\n\nVISUAL IDEA:\n${content.visualIdea}\n\nPOSTING TIP:\n${content.postingTip}`.trim();
    } else {
      allText = textContent;
    }
    await navigator.clipboard.writeText(allText);
    toast({ title: 'Copied!', description: 'Content copied to clipboard' });
  };

  const handlePlatformCopy = async (platform: 'tiktok' | 'reels' | 'shorts') => {
    if (!isStructuredContent) return;
    const formatted = formatForPlatform(content, platform);
    await navigator.clipboard.writeText(formatted);
    const labels = { tiktok: 'TikTok', reels: 'Instagram Reels', shorts: 'YouTube Shorts' };
    toast({ title: `📋 Copied for ${labels[platform]}!`, description: 'Paste it when you post.' });
    setPlatformCopyOpen(false);
  };

  const handleReaction = (r: 'up' | 'down') => {
    const next = reaction === r ? null : r;
    setReaction(next);
    if (reactionKey) {
      if (next) localStorage.setItem(reactionKey, next);
      else localStorage.removeItem(reactionKey);
    }
    if (next === 'up') toast({ title: '🔥 Marked as great!', description: 'Glad this one hit!' });
    if (next === 'down') toast({ title: '👎 Got it', description: "We'll learn from this." });
  };

  const handleExportStoryboardPDF = async () => {
    setExportingPDF(true);
    try {
      const ok = await exportStoryboardPDF(storyboardText, 'creator');
      if (ok) toast({ title: '📄 Storyboard exported!', description: 'PDF downloaded to your device.' });
      else toast({ title: 'No storyboard found', description: 'Ask the AI for a storyboard first.', variant: 'destructive' });
    } catch (e: any) {
      toast({ title: 'Export failed', description: e.message, variant: 'destructive' });
    }
    setExportingPDF(false);
  };

  const buildShareText = () => {
    if (!isStructuredContent) return textContent;
    const hashtags = content.hashtags?.map((t: string) => `#${t}`).join(' ') || '';
    return `${content.hook}\n\n${content.caption}\n\n${hashtags}`;
  };

  const handleShareTikTok = async () => {
    await navigator.clipboard.writeText(buildShareText());
    toast({ title: '📋 TikTok caption copied!', description: 'Paste it into TikTok when you upload.' });
    window.open('https://www.tiktok.com/upload', '_blank');
    setShareOpen(false);
  };

  const handleShareInstagram = async () => {
    await navigator.clipboard.writeText(buildShareText());
    toast({ title: '📋 Instagram caption copied!', description: 'Paste it when you post on Instagram.' });
    window.open('https://www.instagram.com', '_blank');
    setShareOpen(false);
  };

  const handleShareTwitter = () => {
    if (!isStructuredContent) return;
    const tweetText = encodeURIComponent(
      `${content.hook}\n\n${content.hashtags?.slice(0, 3).map((t: string) => `#${t}`).join(' ') || ''}`
    );
    window.open(`https://x.com/intent/tweet?text=${tweetText}`, '_blank');
    setShareOpen(false);
  };

  const Section = ({
    icon: Icon, title, content: text, sectionKey,
  }: { icon: any; title: string; content: string; sectionKey: string }) => (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Icon className="h-4 w-4 text-primary" />
          <h3 className="text-sm font-bold uppercase tracking-wide text-muted-foreground">{title}</h3>
        </div>
        <Button variant="ghost" size="sm" onClick={() => copyToClipboard(text, title)} className="h-7 px-2">
          {copiedSection === title ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
        </Button>
      </div>
      <p className="text-sm leading-relaxed whitespace-pre-wrap">{text}</p>
    </div>
  );

  if (isStructuredContent) {
    return (
      <div className="mb-6 animate-fade-in">
        <div className="max-w-3xl glass-card p-5 sm:p-6 space-y-5">
          <Section icon={Flame} title="HOOK" content={content.hook} sectionKey="hook" />
          <div className="border-t border-border/40" />
          <Section icon={FileText} title="SCRIPT" content={content.script} sectionKey="script" />
          <div className="border-t border-border/40" />
          <Section icon={FileText} title="CAPTION" content={content.caption} sectionKey="caption" />
          <div className="border-t border-border/40" />

          {content.hashtags && content.hashtags.length > 0 && (
            <>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Hash className="h-4 w-4 text-primary" />
                    <h3 className="text-sm font-bold uppercase tracking-wide text-muted-foreground">HASHTAGS</h3>
                  </div>
                  <Button variant="ghost" size="sm" onClick={() => copyToClipboard(content.hashtags.map((t: string) => `#${t}`).join(' '), 'HASHTAGS')} className="h-7 px-2">
                    {copiedSection === 'HASHTAGS' ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
                  </Button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {content.hashtags.map((tag: string) => (
                    <span key={tag} className="px-2.5 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold">#{tag}</span>
                  ))}
                </div>
              </div>
              <div className="border-t border-border/40" />
            </>
          )}

          {content.visualIdea && (
            <>
              <Section icon={Eye} title="VISUAL IDEA" content={content.visualIdea} sectionKey="visual" />
              <div className="border-t border-border/40" />
            </>
          )}

          {content.postingTip && (
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Lightbulb className="h-4 w-4 text-primary" />
                <h3 className="text-sm font-bold uppercase tracking-wide text-muted-foreground">POSTING TIP</h3>
              </div>
              <p className="text-sm bg-primary/5 border border-primary/10 rounded-lg p-3">💡 {content.postingTip}</p>
            </div>
          )}

          {/* ── Action row ── */}
          <div className="border-t border-border/40 pt-4 space-y-3">

            {/* Primary actions */}
            <div className="flex flex-wrap gap-2">
              <Button onClick={copyAll} variant="outline" className="flex-1 min-w-[90px] h-10 font-semibold border-primary/20 hover:bg-primary/10 text-sm">
                <Copy className="mr-1.5 h-3.5 w-3.5" />Copy All
              </Button>

              {/* Platform-specific copy */}
              <Button
                onClick={() => setPlatformCopyOpen(v => !v)}
                variant={platformCopyOpen ? 'default' : 'outline'}
                className={`h-10 px-3 font-semibold text-sm ${platformCopyOpen ? 'bg-primary text-primary-foreground' : 'border-primary/20 hover:bg-primary/10'}`}
                title="Copy for specific platform"
              >
                <FileText className="h-3.5 w-3.5 sm:mr-1.5" />
                <span className="hidden sm:inline">For Platform</span>
              </Button>

              {onRemix && (
                <Button onClick={() => onRemix(remixIteration + 1)} variant="outline" className="h-10 px-3 font-semibold border-accent/40 hover:bg-accent/10" title="Remix">
                  <RotateCw className="h-4 w-4" />
                </Button>
              )}

              <Button onClick={() => setShareOpen(v => !v)} variant={shareOpen ? 'default' : 'outline'} className={`h-10 px-3 font-semibold ${shareOpen ? 'bg-primary text-primary-foreground' : 'border-primary/20 hover:bg-primary/10'}`}>
                <Share2 className="mr-1.5 h-3.5 w-3.5" />Share
              </Button>
            </div>

            {/* Platform copy panel */}
            {platformCopyOpen && (
              <div className="animate-fade-in flex flex-wrap gap-2 p-3 rounded-xl bg-muted/40 border border-border/40">
                <p className="w-full text-[10px] font-bold text-muted-foreground uppercase tracking-wide mb-1">Copy optimised for:</p>
                <button
                  onClick={() => handlePlatformCopy('tiktok')}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-black text-white text-xs font-bold hover:bg-zinc-900 transition-colors flex-1 justify-center min-h-[40px]"
                >
                  <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1V9.01a6.33 6.33 0 00-.79-.05 6.34 6.34 0 00-6.34 6.34 6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.33-6.34V8.99a8.18 8.18 0 004.79 1.53V7.07a4.85 4.85 0 01-1.02-.38z"/>
                  </svg>
                  TikTok
                </button>
                <button
                  onClick={() => handlePlatformCopy('reels')}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold flex-1 justify-center min-h-[40px]"
                  style={{ background: 'linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888)', color: '#fff' }}
                >
                  <Instagram className="h-3.5 w-3.5" />Reels
                </button>
                <button
                  onClick={() => handlePlatformCopy('shorts')}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-red-600 text-white text-xs font-bold hover:bg-red-700 transition-colors flex-1 justify-center min-h-[40px]"
                >
                  <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M23 7.5a4.5 4.5 0 00-4.5-4.5h-13A4.5 4.5 0 001 7.5v9a4.5 4.5 0 004.5 4.5h13A4.5 4.5 0 0023 16.5v-9zM9.75 15.75v-7.5l6 3.75-6 3.75z"/>
                  </svg>
                  Shorts
                </button>
              </div>
            )}

            {/* Share panel */}
            {shareOpen && (
              <div className="animate-fade-in flex flex-wrap gap-2 p-3 rounded-xl bg-muted/40 border border-border/40">
                <button onClick={handleShareTikTok} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-black text-white text-xs font-bold hover:bg-black/80 transition-colors flex-1 justify-center min-w-[80px] min-h-[40px]">
                  <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1V9.01a6.33 6.33 0 00-.79-.05 6.34 6.34 0 00-6.34 6.34 6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.33-6.34V8.99a8.18 8.18 0 004.79 1.53V7.07a4.85 4.85 0 01-1.02-.38z"/>
                  </svg>
                  TikTok
                </button>
                <button onClick={handleShareInstagram} className="flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-bold flex-1 justify-center min-w-[80px] min-h-[40px]" style={{ background: 'linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888)', color: '#fff' }}>
                  <Instagram className="h-3.5 w-3.5" />Instagram
                </button>
                <button onClick={handleShareTwitter} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-black text-white text-xs font-bold hover:bg-zinc-800 transition-colors flex-1 justify-center min-w-[80px] min-h-[40px]">
                  <Twitter className="h-3.5 w-3.5" />X / Twitter
                </button>
              </div>
            )}

            {/* Storyboard export */}
            {hasStoryboard && (
              <Button
                onClick={handleExportStoryboardPDF}
                disabled={exportingPDF}
                variant="outline"
                className="w-full h-10 gap-2 border-primary/20 hover:bg-primary/10 font-semibold text-sm"
              >
                {exportingPDF
                  ? <><div className="h-3.5 w-3.5 rounded-full border-2 border-primary/30 border-t-primary animate-spin" />Exporting…</>
                  : <><Table2 className="h-3.5 w-3.5" /><Download className="h-3.5 w-3.5" />Download Storyboard PDF</>
                }
              </Button>
            )}

            {/* Thumbs up / down reactions */}
            <div className="flex items-center gap-3 pt-1">
              <span className="text-xs text-muted-foreground">Was this useful?</span>
              <button
                onClick={() => handleReaction('up')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold transition-all border ${
                  reaction === 'up'
                    ? 'bg-green-500/20 text-green-400 border-green-500/40 scale-105'
                    : 'bg-transparent border-border/50 text-muted-foreground hover:border-green-500/40 hover:text-green-400 hover:bg-green-500/10'
                }`}
              >
                <ThumbsUp className="h-3.5 w-3.5" />Yes
              </button>
              <button
                onClick={() => handleReaction('down')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold transition-all border ${
                  reaction === 'down'
                    ? 'bg-red-500/20 text-red-400 border-red-500/40 scale-105'
                    : 'bg-transparent border-border/50 text-muted-foreground hover:border-red-500/40 hover:text-red-400 hover:bg-red-500/10'
                }`}
              >
                <ThumbsDown className="h-3.5 w-3.5" />No
              </button>
            </div>
          </div>

          <ContentReviewPanel
            hook={content.hook}
            script={content.script}
            caption={content.caption}
            hashtags={content.hashtags || []}
            niche={content.niche || ''}
            vibe={content.vibe || ''}
          />
        </div>
      </div>
    );
  }

  // ── Conversational message ────────────────────────────────────────────────

  const formatText = (text: string) => {
    const lines = text.split('\n');
    return lines.map((line, i) => {
      if (line.startsWith('### ')) return <h3 key={i} className="text-sm font-bold mb-2 mt-3">{line.slice(4)}</h3>;
      if (line.startsWith('## ')) return <h2 key={i} className="text-base font-bold mb-2 mt-3">{line.slice(3)}</h2>;
      if (line.startsWith('# ')) return <h1 key={i} className="text-lg font-bold mb-2 mt-3">{line.slice(2)}</h1>;

      // Table row — render inside a scrollable div
      if (line.trim().startsWith('|')) {
        return (
          <span key={i} className="block font-mono text-xs text-muted-foreground leading-relaxed">
            {line}
          </span>
        );
      }

      if (line.match(/^[-*]\s/)) return <li key={i} className="text-sm ml-4 mb-1">{line.slice(2)}</li>;
      if (line.match(/^\d+\.\s/)) return <li key={i} className="text-sm ml-4 mb-1">{line.replace(/^\d+\.\s/, '')}</li>;
      const parts = line.split(/\*\*(.*?)\*\*/g);
      const formatted = parts.map((part, j) => j % 2 === 1 ? <strong key={j} className="font-semibold">{part}</strong> : part);
      if (!line.trim()) return <br key={i} />;
      return <p key={i} className="text-sm leading-relaxed mb-3">{formatted}</p>;
    });
  };

  return (
    <div className="mb-6 animate-fade-in">
      <div className="max-w-3xl">
        <div className="flex items-start gap-3">
          <div className="mt-1 p-2 rounded-lg bg-primary/10 flex-shrink-0">
            <Sparkles className="h-4 w-4 text-primary" />
          </div>
          <div className="flex-1 min-w-0 space-y-3">
            <div className="space-y-1 overflow-x-auto">{formatText(textContent)}</div>
            <div className="flex items-center gap-2 flex-wrap">
              <Button onClick={copyAll} variant="ghost" size="sm" className="h-8">
                <Copy className="mr-1.5 h-3.5 w-3.5" />Copy
              </Button>
              {onRemix && (
                <Button onClick={() => onRemix(remixIteration + 1)} variant="ghost" size="sm" className="h-8" title="Remix">
                  <RotateCw className="h-3.5 w-3.5" />
                </Button>
              )}

              {/* Storyboard PDF export for conversational storyboard responses */}
              {hasStoryboard && (
                <Button
                  onClick={handleExportStoryboardPDF}
                  disabled={exportingPDF}
                  variant="ghost"
                  size="sm"
                  className="h-8 gap-1.5 text-primary hover:text-primary hover:bg-primary/10"
                >
                  {exportingPDF
                    ? <div className="h-3.5 w-3.5 rounded-full border-2 border-primary/30 border-t-primary animate-spin" />
                    : <><Table2 className="h-3.5 w-3.5" /><Download className="h-3 w-3" /></>
                  }
                  <span className="text-xs">Storyboard PDF</span>
                </Button>
              )}

              {/* Inline reactions for conversational */}
              <div className="flex items-center gap-1.5 ml-auto">
                <button onClick={() => handleReaction('up')} className={`p-1.5 rounded-lg transition-all ${reaction === 'up' ? 'text-green-400 bg-green-500/10' : 'text-muted-foreground hover:text-green-400'}`}>
                  <ThumbsUp className="h-3.5 w-3.5" />
                </button>
                <button onClick={() => handleReaction('down')} className={`p-1.5 rounded-lg transition-all ${reaction === 'down' ? 'text-red-400 bg-red-500/10' : 'text-muted-foreground hover:text-red-400'}`}>
                  <ThumbsDown className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
